export const profileActionTypes = {
  ADD_POST: 'ADD_POST',
  SET_USER_PROFILE: 'SET_USER_PROFILE',
  SET_STATUS: 'SET_STATUS',
  DELETE_POST: 'DELETE_POST',
  SAVE_PHOTO_SUCCESS: 'SAVE_PHOTO_SUCCESS',
  SAVE_PROFILE_SUCCESS: 'SAVE_PROFILE_SUCCESS',
} as const
