export const usersActionTypes = {
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
  SET_USERS: 'SET_USERS',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_USERS_COUNT: 'SET_TOTAL_USERS_COUNT',
  TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
  TOGGLE_IS_FOLLOWING_PROGRESS: 'TOGGLE_IS_FOLLOWING_PROGRESS',
}
